CREATE TABLE "public"."roles"
(
    "id"        int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title"     TEXT NOT NULL,
    "createdAt" timestamp DEFAULT now(),
    "headerKey" TEXT NOT NULL,

    CONSTRAINT "UNIQUE_ROLES_HEADER_KEY" UNIQUE ("headerKey")
);

INSERT INTO "public"."roles" ("id", "title", "createdAt", "headerKey")
VALUES (0, 'Внутренний сервис', NOW(), 'SERVICE');

INSERT INTO "public"."roles" ("id", "title", "createdAt", "headerKey")
VALUES (1, 'Пользователь приложения', NOW(), 'USER');


CREATE TABLE "public"."users"
(
    "id"            int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "firstName"     TEXT      NOT NULL,
    "lastName"      TEXT      NOT NULL,
    "email"         TEXT      NOT NULL,
    "username"      TEXT      NOT NULL,
    "gender"        TEXT      NOT NULL,
    "roleId"        int4      NOT NULL references "public"."roles" (id),
    "status"        TEXT      NOT NULL,
    "avatarImageId" int4               DEFAULT NULL,
    "birthDate"     timestamp NOT NULL,
    "password"      TEXT      NOT NULL,
    "createdAt"     timestamp NOT NULL DEFAULT now(),
    "updatedAt"     timestamp NOT NULL DEFAULT now(),

    CONSTRAINT "UNIQUE_USERS_EMAIL" UNIQUE ("email", "username")
);
