CREATE TYPE role_enum AS ENUM ('ADMIN', 'CONTENT_MANAGER', 'DEFAULT_USER');

CREATE TABLE users
(
    id            BIGINT       PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    role          role_enum    NOT NULL     DEFAULT 'DEFAULT_USER',
    username      TEXT         NOT NULL,
    email         TEXT         NOT NULL     UNIQUE,
    password      TEXT         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL     DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL     DEFAULT CURRENT_TIMESTAMP,
    image         OID
);
