CREATE TABLE IF NOT EXISTS games
(
    id                   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_player_id      BIGINT REFERENCES users(id),
    second_player_id     BIGINT REFERENCES users(id),
    winner_id            BIGINT REFERENCES users(id) CHECK (winner_id IN (first_player_id, second_player_id)),
    metatopic_id         BIGINT REFERENCES metatopics(id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
