CREATE TABLE IF NOT EXISTS achievements
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users_achievements
(
    user_id                   BIGINT REFERENCES users(id) ON DELETE CASCADE,
    achievement_id            BIGINT REFERENCES achievements(id) ON DELETE CASCADE,
    CONSTRAINT unique_users_achievements UNIQUE (user_id, achievement_id)
);
