name: Deploy User Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run Go linter
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Run Go tests
      run: |
        go test ./... -v
        
    - name: Deploy application via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

        script: |
          set -e
          echo "Cloning the repository..."
          cd /var/www/deploy/code/UserService/ || (mkdir /var/www/deploy/code/UserService/ && cd /var/www/deploy/code/UserService/)
          git fetch --all
          echo "Checkout to ${{ github.sha }}"
          git checkout ${{ github.sha }}
          
          echo "Building and restarting Docker Compose..."
          cd /var/www/deploy/
          docker compose -f docker-compose-services.yml up user_service -d --build
